# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Ashoka\EclipseProjects\fdr_mix_model\src\epicUIelements\dlgSelectVars.ui'
#
# Created: Sun Oct 19 21:36:37 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mdlgSelectVars(object):
    def setupUi(self, mdlgSelectVars):
        mdlgSelectVars.setObjectName("mdlgSelectVars")
        mdlgSelectVars.resize(502, 550)
        self.buttonBox = QtGui.QDialogButtonBox(mdlgSelectVars)
        self.buttonBox.setGeometry(QtCore.QRect(320, 420, 111, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(mdlgSelectVars)
        self.label.setGeometry(QtCore.QRect(11, 10, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtGui.QFrame(mdlgSelectVars)
        self.line.setGeometry(QtCore.QRect(10, 30, 481, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtGui.QLabel(mdlgSelectVars)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.mListViewCols = QtGui.QListWidget(mdlgSelectVars)
        self.mListViewCols.setGeometry(QtCore.QRect(10, 70, 251, 291))
        self.mListViewCols.setObjectName("mListViewCols")
        self.mBtnZ = QtGui.QPushButton(mdlgSelectVars)
        self.mBtnZ.setGeometry(QtCore.QRect(270, 230, 50, 25))
        self.mBtnZ.setObjectName("mBtnZ")
        self.mLineEditY = QtGui.QLineEdit(mdlgSelectVars)
        self.mLineEditY.setGeometry(QtCore.QRect(330, 180, 161, 25))
        self.mLineEditY.setReadOnly(False)
        self.mLineEditY.setObjectName("mLineEditY")
        self.label_6 = QtGui.QLabel(mdlgSelectVars)
        self.label_6.setGeometry(QtCore.QRect(330, 260, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mLineEditX = QtGui.QLineEdit(mdlgSelectVars)
        self.mLineEditX.setGeometry(QtCore.QRect(330, 130, 161, 25))
        self.mLineEditX.setReadOnly(False)
        self.mLineEditX.setObjectName("mLineEditX")
        self.mLineEditPepSeq = QtGui.QLineEdit(mdlgSelectVars)
        self.mLineEditPepSeq.setGeometry(QtCore.QRect(330, 80, 161, 25))
        self.mLineEditPepSeq.setReadOnly(False)
        self.mLineEditPepSeq.setObjectName("mLineEditPepSeq")
        self.mBtnX = QtGui.QPushButton(mdlgSelectVars)
        self.mBtnX.setGeometry(QtCore.QRect(270, 130, 50, 25))
        self.mBtnX.setObjectName("mBtnX")
        self.label_3 = QtGui.QLabel(mdlgSelectVars)
        self.label_3.setGeometry(QtCore.QRect(330, 60, 147, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.mLineEditCS = QtGui.QLineEdit(mdlgSelectVars)
        self.mLineEditCS.setGeometry(QtCore.QRect(330, 280, 161, 25))
        self.mLineEditCS.setReadOnly(False)
        self.mLineEditCS.setObjectName("mLineEditCS")
        self.mBtnY = QtGui.QPushButton(mdlgSelectVars)
        self.mBtnY.setGeometry(QtCore.QRect(270, 180, 50, 25))
        self.mBtnY.setObjectName("mBtnY")
        self.mLineEditZ = QtGui.QLineEdit(mdlgSelectVars)
        self.mLineEditZ.setGeometry(QtCore.QRect(330, 230, 161, 25))
        self.mLineEditZ.setReadOnly(False)
        self.mLineEditZ.setObjectName("mLineEditZ")
        self.mBtnPepSeq = QtGui.QPushButton(mdlgSelectVars)
        self.mBtnPepSeq.setGeometry(QtCore.QRect(270, 80, 50, 25))
        self.mBtnPepSeq.setObjectName("mBtnPepSeq")
        self.label_4 = QtGui.QLabel(mdlgSelectVars)
        self.label_4.setGeometry(QtCore.QRect(330, 110, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(mdlgSelectVars)
        self.label_5.setGeometry(QtCore.QRect(330, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.mBtnCS = QtGui.QPushButton(mdlgSelectVars)
        self.mBtnCS.setGeometry(QtCore.QRect(270, 280, 50, 25))
        self.mBtnCS.setObjectName("mBtnCS")
        self.label_9 = QtGui.QLabel(mdlgSelectVars)
        self.label_9.setGeometry(QtCore.QRect(330, 210, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtGui.QLabel(mdlgSelectVars)
        self.label_7.setGeometry(QtCore.QRect(330, 310, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.mLineEditTrypState = QtGui.QLineEdit(mdlgSelectVars)
        self.mLineEditTrypState.setGeometry(QtCore.QRect(330, 330, 161, 25))
        self.mLineEditTrypState.setReadOnly(False)
        self.mLineEditTrypState.setObjectName("mLineEditTrypState")
        self.mBtnTrypState = QtGui.QPushButton(mdlgSelectVars)
        self.mBtnTrypState.setGeometry(QtCore.QRect(270, 330, 50, 25))
        self.mBtnTrypState.setObjectName("mBtnTrypState")
        self.mtoolBox = QtGui.QToolBox(mdlgSelectVars)
        self.mtoolBox.setGeometry(QtCore.QRect(10, 370, 251, 171))
        self.mtoolBox.setFrameShape(QtGui.QFrame.Panel)
        self.mtoolBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.mtoolBox.setObjectName("mtoolBox")
        self.CSstates = QtGui.QWidget()
        self.CSstates.setGeometry(QtCore.QRect(0, 0, 249, 113))
        self.CSstates.setObjectName("CSstates")
        self.mchkBoxCSother = QtGui.QCheckBox(self.CSstates)
        self.mchkBoxCSother.setGeometry(QtCore.QRect(30, 90, 151, 18))
        self.mchkBoxCSother.setChecked(False)
        self.mchkBoxCSother.setObjectName("mchkBoxCSother")
        self.mchkBoxCS3 = QtGui.QCheckBox(self.CSstates)
        self.mchkBoxCS3.setGeometry(QtCore.QRect(30, 60, 101, 18))
        self.mchkBoxCS3.setChecked(False)
        self.mchkBoxCS3.setObjectName("mchkBoxCS3")
        self.mchkBoxCS2 = QtGui.QCheckBox(self.CSstates)
        self.mchkBoxCS2.setGeometry(QtCore.QRect(30, 30, 101, 18))
        self.mchkBoxCS2.setChecked(True)
        self.mchkBoxCS2.setObjectName("mchkBoxCS2")
        self.mchkBoxCS1 = QtGui.QCheckBox(self.CSstates)
        self.mchkBoxCS1.setGeometry(QtCore.QRect(30, 0, 101, 18))
        self.mchkBoxCS1.setChecked(False)
        self.mchkBoxCS1.setObjectName("mchkBoxCS1")
        self.mtoolBox.addItem(self.CSstates, "")
        self.TrState = QtGui.QWidget()
        self.TrState.setGeometry(QtCore.QRect(0, 0, 249, 113))
        self.TrState.setObjectName("TrState")
        self.mchkBoxFull = QtGui.QCheckBox(self.TrState)
        self.mchkBoxFull.setGeometry(QtCore.QRect(30, 80, 71, 18))
        self.mchkBoxFull.setChecked(True)
        self.mchkBoxFull.setObjectName("mchkBoxFull")
        self.mchkBoxNone = QtGui.QCheckBox(self.TrState)
        self.mchkBoxNone.setGeometry(QtCore.QRect(30, 0, 71, 18))
        self.mchkBoxNone.setChecked(False)
        self.mchkBoxNone.setObjectName("mchkBoxNone")
        self.mchkBoxPartial = QtGui.QCheckBox(self.TrState)
        self.mchkBoxPartial.setGeometry(QtCore.QRect(30, 40, 71, 18))
        self.mchkBoxPartial.setChecked(False)
        self.mchkBoxPartial.setObjectName("mchkBoxPartial")
        self.mtoolBox.addItem(self.TrState, "")

        self.retranslateUi(mdlgSelectVars)
        self.mtoolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), mdlgSelectVars.reject)
        QtCore.QMetaObject.connectSlotsByName(mdlgSelectVars)

    def retranslateUi(self, mdlgSelectVars):
        mdlgSelectVars.setWindowTitle(QtGui.QApplication.translate("mdlgSelectVars", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mdlgSelectVars", "Select Variables :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mdlgSelectVars", "Available Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.mBtnZ.setText(QtGui.QApplication.translate("mdlgSelectVars", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mdlgSelectVars", "Charge State : (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.mBtnX.setText(QtGui.QApplication.translate("mdlgSelectVars", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mdlgSelectVars", "Peptide Sequence : (Req.)", None, QtGui.QApplication.UnicodeUTF8))
        self.mBtnY.setText(QtGui.QApplication.translate("mdlgSelectVars", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.mBtnPepSeq.setText(QtGui.QApplication.translate("mdlgSelectVars", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mdlgSelectVars", "X variable : (Req.)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mdlgSelectVars", "Y Variable : (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.mBtnCS.setText(QtGui.QApplication.translate("mdlgSelectVars", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mdlgSelectVars", "Z Variable : (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mdlgSelectVars", "Tryptic State : (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.mBtnTrypState.setText(QtGui.QApplication.translate("mdlgSelectVars", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCSother.setText(QtGui.QApplication.translate("mdlgSelectVars", "Charge State 4 and above", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS3.setText(QtGui.QApplication.translate("mdlgSelectVars", "Charge State 3", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS2.setText(QtGui.QApplication.translate("mdlgSelectVars", "Charge State 2", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS1.setText(QtGui.QApplication.translate("mdlgSelectVars", "Charge State 1", None, QtGui.QApplication.UnicodeUTF8))
        self.mtoolBox.setItemText(self.mtoolBox.indexOf(self.CSstates), QtGui.QApplication.translate("mdlgSelectVars", "Select Charge States:", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxFull.setText(QtGui.QApplication.translate("mdlgSelectVars", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxNone.setText(QtGui.QApplication.translate("mdlgSelectVars", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxPartial.setText(QtGui.QApplication.translate("mdlgSelectVars", "Partial", None, QtGui.QApplication.UnicodeUTF8))
        self.mtoolBox.setItemText(self.mtoolBox.indexOf(self.TrState), QtGui.QApplication.translate("mdlgSelectVars", "Select Tryptic States:", None, QtGui.QApplication.UnicodeUTF8))

