# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Ashoka\EclipseProjects\fdr_mix_model\src\epicUIelements\dlgPlotOptions.ui'
#
# Created: Tue Oct 14 00:00:41 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dlgPlotOptions(object):
    def setupUi(self, dlgPlotOptions):
        dlgPlotOptions.setObjectName("dlgPlotOptions")
        dlgPlotOptions.setWindowModality(QtCore.Qt.WindowModal)
        dlgPlotOptions.resize(545, 278)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgPlotOptions.sizePolicy().hasHeightForWidth())
        dlgPlotOptions.setSizePolicy(sizePolicy)
        dlgPlotOptions.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonBox = QtGui.QDialogButtonBox(dlgPlotOptions)
        self.buttonBox.setGeometry(QtCore.QRect(9, 599, 731, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.mcmbBLineW = QtGui.QComboBox(dlgPlotOptions)
        self.mcmbBLineW.setGeometry(QtCore.QRect(400, 100, 121, 20))
        self.mcmbBLineW.setEditable(True)
        self.mcmbBLineW.setObjectName("mcmbBLineW")
        self.mcmbBLineStyle = QtGui.QComboBox(dlgPlotOptions)
        self.mcmbBLineStyle.setGeometry(QtCore.QRect(400, 70, 121, 20))
        self.mcmbBLineStyle.setObjectName("mcmbBLineStyle")
        self.mcmbBMarkerSize = QtGui.QComboBox(dlgPlotOptions)
        self.mcmbBMarkerSize.setGeometry(QtCore.QRect(400, 160, 121, 20))
        self.mcmbBMarkerSize.setEditable(True)
        self.mcmbBMarkerSize.setObjectName("mcmbBMarkerSize")
        self.label_7 = QtGui.QLabel(dlgPlotOptions)
        self.label_7.setGeometry(QtCore.QRect(329, 190, 82, 20))
        self.label_7.setObjectName("label_7")
        self.mtoolBtnColor = ColorButton(dlgPlotOptions)
        self.mtoolBtnColor.setEnabled(True)
        self.mtoolBtnColor.setGeometry(QtCore.QRect(400, 190, 121, 21))
        self.mtoolBtnColor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mtoolBtnColor.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.mtoolBtnColor.setObjectName("mtoolBtnColor")
        self.label_2 = QtGui.QLabel(dlgPlotOptions)
        self.label_2.setGeometry(QtCore.QRect(339, 100, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtGui.QLabel(dlgPlotOptions)
        self.label_6.setGeometry(QtCore.QRect(335, 160, 82, 20))
        self.label_6.setObjectName("label_6")
        self.label = QtGui.QLabel(dlgPlotOptions)
        self.label.setGeometry(QtCore.QRect(342, 70, 82, 20))
        self.label.setObjectName("label")
        self.label_5 = QtGui.QLabel(dlgPlotOptions)
        self.label_5.setGeometry(QtCore.QRect(330, 130, 82, 20))
        self.label_5.setObjectName("label_5")
        self.mcmbBMarkerStyle = QtGui.QComboBox(dlgPlotOptions)
        self.mcmbBMarkerStyle.setGeometry(QtCore.QRect(400, 130, 121, 20))
        self.mcmbBMarkerStyle.setObjectName("mcmbBMarkerStyle")
        self.mlineEditYmin = QtGui.QLineEdit(dlgPlotOptions)
        self.mlineEditYmin.setGeometry(QtCore.QRect(202, 70, 117, 20))
        self.mlineEditYmin.setObjectName("mlineEditYmin")
        self.min_label = QtGui.QLabel(dlgPlotOptions)
        self.min_label.setGeometry(QtCore.QRect(26, 70, 48, 20))
        self.min_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.min_label.setObjectName("min_label")
        self.mchkBoxLogX = QtGui.QCheckBox(dlgPlotOptions)
        self.mchkBoxLogX.setGeometry(QtCore.QRect(80, 150, 83, 23))
        self.mchkBoxLogX.setObjectName("mchkBoxLogX")
        self.mlineEditTitle = QtGui.QLineEdit(dlgPlotOptions)
        self.mlineEditTitle.setGeometry(QtCore.QRect(77, 16, 241, 21))
        self.mlineEditTitle.setObjectName("mlineEditTitle")
        self.mchkBoxGrid = QtGui.QCheckBox(dlgPlotOptions)
        self.mchkBoxGrid.setGeometry(QtCore.QRect(80, 180, 83, 23))
        self.mchkBoxGrid.setChecked(True)
        self.mchkBoxGrid.setObjectName("mchkBoxGrid")
        self.mlineEditYmax = QtGui.QLineEdit(dlgPlotOptions)
        self.mlineEditYmax.setGeometry(QtCore.QRect(202, 96, 117, 20))
        self.mlineEditYmax.setObjectName("mlineEditYmax")
        self.mlineEditYlabel = QtGui.QLineEdit(dlgPlotOptions)
        self.mlineEditYlabel.setGeometry(QtCore.QRect(202, 122, 117, 20))
        self.mlineEditYlabel.setObjectName("mlineEditYlabel")
        self.label_4 = QtGui.QLabel(dlgPlotOptions)
        self.label_4.setGeometry(QtCore.QRect(202, 33, 117, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.mlineEditXmin = QtGui.QLineEdit(dlgPlotOptions)
        self.mlineEditXmin.setGeometry(QtCore.QRect(80, 70, 116, 20))
        self.mlineEditXmin.setObjectName("mlineEditXmin")
        self.plot_title_label = QtGui.QLabel(dlgPlotOptions)
        self.plot_title_label.setGeometry(QtCore.QRect(10, 10, 61, 27))
        self.plot_title_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.plot_title_label.setObjectName("plot_title_label")
        self.mchkBoxLogY = QtGui.QCheckBox(dlgPlotOptions)
        self.mchkBoxLogY.setGeometry(QtCore.QRect(200, 150, 83, 23))
        self.mchkBoxLogY.setObjectName("mchkBoxLogY")
        self.mlineEditXmax = QtGui.QLineEdit(dlgPlotOptions)
        self.mlineEditXmax.setGeometry(QtCore.QRect(80, 96, 116, 20))
        self.mlineEditXmax.setObjectName("mlineEditXmax")
        self.mlineEditXlabel = QtGui.QLineEdit(dlgPlotOptions)
        self.mlineEditXlabel.setGeometry(QtCore.QRect(80, 122, 116, 20))
        self.mlineEditXlabel.setObjectName("mlineEditXlabel")
        self.axis_text_label = QtGui.QLabel(dlgPlotOptions)
        self.axis_text_label.setGeometry(QtCore.QRect(26, 122, 48, 20))
        self.axis_text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.axis_text_label.setObjectName("axis_text_label")
        self.label_3 = QtGui.QLabel(dlgPlotOptions)
        self.label_3.setGeometry(QtCore.QRect(80, 33, 116, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.max_label = QtGui.QLabel(dlgPlotOptions)
        self.max_label.setGeometry(QtCore.QRect(26, 96, 48, 20))
        self.max_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_label.setObjectName("max_label")
        self.mBtnBox = QtGui.QDialogButtonBox(dlgPlotOptions)
        self.mBtnBox.setGeometry(QtCore.QRect(100, 240, 431, 25))
        self.mBtnBox.setOrientation(QtCore.Qt.Horizontal)
        self.mBtnBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.mBtnBox.setObjectName("mBtnBox")
        self.line = QtGui.QFrame(dlgPlotOptions)
        self.line.setGeometry(QtCore.QRect(10, 220, 521, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(dlgPlotOptions)
        QtCore.QObject.connect(self.mBtnBox, QtCore.SIGNAL("accepted()"), dlgPlotOptions.accept)
        QtCore.QObject.connect(self.mBtnBox, QtCore.SIGNAL("rejected()"), dlgPlotOptions.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgPlotOptions)

    def retranslateUi(self, dlgPlotOptions):
        dlgPlotOptions.setWindowTitle(QtGui.QApplication.translate("dlgPlotOptions", "Plot Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgPlotOptions", "Marker Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.mtoolBtnColor.setText(QtGui.QApplication.translate("dlgPlotOptions", "Select Color...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dlgPlotOptions", "Line Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgPlotOptions", "Marker Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgPlotOptions", "Line Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgPlotOptions", "Marker Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.min_label.setText(QtGui.QApplication.translate("dlgPlotOptions", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxLogX.setText(QtGui.QApplication.translate("dlgPlotOptions", "Log X Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.mlineEditTitle.setText(QtGui.QApplication.translate("dlgPlotOptions", "Plot Title", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxGrid.setText(QtGui.QApplication.translate("dlgPlotOptions", "Grid Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.mlineEditYlabel.setText(QtGui.QApplication.translate("dlgPlotOptions", "y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgPlotOptions", "Y Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_title_label.setText(QtGui.QApplication.translate("dlgPlotOptions", "Plot Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxLogY.setText(QtGui.QApplication.translate("dlgPlotOptions", "Log Y Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.mlineEditXlabel.setText(QtGui.QApplication.translate("dlgPlotOptions", "x-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.axis_text_label.setText(QtGui.QApplication.translate("dlgPlotOptions", "Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlgPlotOptions", "X Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.max_label.setText(QtGui.QApplication.translate("dlgPlotOptions", "Maximum:", None, QtGui.QApplication.UnicodeUTF8))

from colorbutton import ColorButton
