# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Ashoka\EclipseProjects\fdr_mix_model\src\epicUIelements\dlgSpectrumMillPara.ui'
#
# Created: Sun Oct 26 21:58:28 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mdlgSpectrumMillPara(object):
    def setupUi(self, mdlgSpectrumMillPara):
        mdlgSpectrumMillPara.setObjectName("mdlgSpectrumMillPara")
        mdlgSpectrumMillPara.resize(343, 307)
        self.buttonBox = QtGui.QDialogButtonBox(mdlgSpectrumMillPara)
        self.buttonBox.setGeometry(QtCore.QRect(250, 60, 81, 101))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line_2 = QtGui.QFrame(mdlgSpectrumMillPara)
        self.line_2.setGeometry(QtCore.QRect(19, 290, 311, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtGui.QFrame(mdlgSpectrumMillPara)
        self.line.setGeometry(QtCore.QRect(19, 30, 311, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mlineEditDelCn2threh = QtGui.QLineEdit(mdlgSpectrumMillPara)
        self.mlineEditDelCn2threh.setGeometry(QtCore.QRect(170, 210, 61, 21))
        self.mlineEditDelCn2threh.setObjectName("mlineEditDelCn2threh")
        self.label_8 = QtGui.QLabel(mdlgSpectrumMillPara)
        self.label_8.setGeometry(QtCore.QRect(30, 210, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame = QtGui.QFrame(mdlgSpectrumMillPara)
        self.frame.setGeometry(QtCore.QRect(19, 250, 211, 31))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.mchkBoxByPass = QtGui.QCheckBox(self.frame)
        self.mchkBoxByPass.setGeometry(QtCore.QRect(8, 7, 181, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.mchkBoxByPass.setFont(font)
        self.mchkBoxByPass.setChecked(False)
        self.mchkBoxByPass.setObjectName("mchkBoxByPass")
        self.groupBox = QtGui.QGroupBox(mdlgSpectrumMillPara)
        self.groupBox.setGeometry(QtCore.QRect(19, 50, 211, 151))
        self.groupBox.setObjectName("groupBox")
        self.mchkBoxCS1 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS1.setGeometry(QtCore.QRect(30, 20, 101, 18))
        self.mchkBoxCS1.setChecked(True)
        self.mchkBoxCS1.setObjectName("mchkBoxCS1")
        self.mchkBoxCS3 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS3.setGeometry(QtCore.QRect(30, 80, 101, 18))
        self.mchkBoxCS3.setChecked(True)
        self.mchkBoxCS3.setObjectName("mchkBoxCS3")
        self.mchkBoxCS2 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS2.setGeometry(QtCore.QRect(30, 50, 101, 18))
        self.mchkBoxCS2.setChecked(True)
        self.mchkBoxCS2.setObjectName("mchkBoxCS2")
        self.mchkBoxCSother = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCSother.setGeometry(QtCore.QRect(30, 110, 151, 18))
        self.mchkBoxCSother.setChecked(True)
        self.mchkBoxCSother.setObjectName("mchkBoxCSother")
        self.label = QtGui.QLabel(mdlgSpectrumMillPara)
        self.label.setGeometry(QtCore.QRect(20, 10, 231, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(mdlgSpectrumMillPara)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), mdlgSpectrumMillPara.reject)
        QtCore.QMetaObject.connectSlotsByName(mdlgSpectrumMillPara)

    def retranslateUi(self, mdlgSpectrumMillPara):
        mdlgSpectrumMillPara.setWindowTitle(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Spectrum Mill", None, QtGui.QApplication.UnicodeUTF8))
        self.mlineEditDelCn2threh.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "ΔFwdRev Score Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxByPass.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Bypass all the above filters", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Select Charge States", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS1.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Charge State 1", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS3.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Charge State 3", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS2.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Charge State 2", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCSother.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Charge State 4 and above", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mdlgSpectrumMillPara", "Select Spectrum Mill Parameters :", None, QtGui.QApplication.UnicodeUTF8))

