# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Research\Python\fdr_mix_model\src\epicUIelements\dlgEMparameters.ui'
#
# Created: Tue Oct 21 09:36:46 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mdlgEMparameters(object):
    def setupUi(self, mdlgEMparameters):
        mdlgEMparameters.setObjectName("mdlgEMparameters")
        mdlgEMparameters.resize(480, 431)
        self.buttonBox = QtGui.QDialogButtonBox(mdlgEMparameters)
        self.buttonBox.setGeometry(QtCore.QRect(110, 390, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(mdlgEMparameters)
        self.label.setGeometry(QtCore.QRect(21, 20, 341, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtGui.QFrame(mdlgEMparameters)
        self.line.setGeometry(QtCore.QRect(20, 40, 441, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(mdlgEMparameters)
        self.line_2.setGeometry(QtCore.QRect(20, 370, 441, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.mstkWidgEM = QtGui.QStackedWidget(mdlgEMparameters)
        self.mstkWidgEM.setGeometry(QtCore.QRect(10, 90, 451, 281))
        self.mstkWidgEM.setFrameShape(QtGui.QFrame.NoFrame)
        self.mstkWidgEM.setObjectName("mstkWidgEM")
        self.page1D = QtGui.QWidget()
        self.page1D.setObjectName("page1D")
        self.groupBox_2 = QtGui.QGroupBox(self.page1D)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 191, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(30, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.mLineEd1DmuF = QtGui.QLineEdit(self.groupBox_2)
        self.mLineEd1DmuF.setGeometry(QtCore.QRect(80, 30, 81, 21))
        self.mLineEd1DmuF.setObjectName("mLineEd1DmuF")
        self.mLineEd1DsigF = QtGui.QLineEdit(self.groupBox_2)
        self.mLineEd1DsigF.setGeometry(QtCore.QRect(80, 90, 81, 21))
        self.mLineEd1DsigF.setObjectName("mLineEd1DsigF")
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(30, 90, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.mLineEd1DpF = QtGui.QLineEdit(self.groupBox_2)
        self.mLineEd1DpF.setGeometry(QtCore.QRect(80, 150, 81, 21))
        self.mLineEd1DpF.setObjectName("mLineEd1DpF")
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(10, 150, 72, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_26 = QtGui.QLabel(self.page1D)
        self.label_26.setGeometry(QtCore.QRect(230, 250, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_24 = QtGui.QLabel(self.page1D)
        self.label_24.setGeometry(QtCore.QRect(20, 250, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.mLineEd1DTol = QtGui.QLineEdit(self.page1D)
        self.mLineEd1DTol.setGeometry(QtCore.QRect(380, 250, 48, 21))
        self.mLineEd1DTol.setObjectName("mLineEd1DTol")
        self.groupBox_4 = QtGui.QGroupBox(self.page1D)
        self.groupBox_4.setGeometry(QtCore.QRect(250, 40, 181, 191))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.mLineEd1DmuT = QtGui.QLineEdit(self.groupBox_4)
        self.mLineEd1DmuT.setGeometry(QtCore.QRect(70, 30, 81, 21))
        self.mLineEd1DmuT.setObjectName("mLineEd1DmuT")
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 90, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setObjectName("label_21")
        self.mLineEd1DsigT = QtGui.QLineEdit(self.groupBox_4)
        self.mLineEd1DsigT.setGeometry(QtCore.QRect(70, 90, 81, 21))
        self.mLineEd1DsigT.setObjectName("mLineEd1DsigT")
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(30, 150, 111, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.mLineEd1DMaxIter = QtGui.QLineEdit(self.page1D)
        self.mLineEd1DMaxIter.setGeometry(QtCore.QRect(120, 250, 61, 21))
        self.mLineEd1DMaxIter.setObjectName("mLineEd1DMaxIter")
        self.label_25 = QtGui.QLabel(self.page1D)
        self.label_25.setGeometry(QtCore.QRect(430, 250, 21, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.mcmbBox1DX = QtGui.QComboBox(self.page1D)
        self.mcmbBox1DX.setGeometry(QtCore.QRect(80, 10, 101, 22))
        self.mcmbBox1DX.setObjectName("mcmbBox1DX")
        self.label_22 = QtGui.QLabel(self.page1D)
        self.label_22.setGeometry(QtCore.QRect(20, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.mstkWidgEM.addWidget(self.page1D)
        self.page2D = QtGui.QWidget()
        self.page2D.setObjectName("page2D")
        self.label_15 = QtGui.QLabel(self.page2D)
        self.label_15.setGeometry(QtCore.QRect(430, 250, 21, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.groupBox_3 = QtGui.QGroupBox(self.page2D)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 40, 181, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.mLineEd2DmuYT = QtGui.QLineEdit(self.groupBox_3)
        self.mLineEd2DmuYT.setGeometry(QtCore.QRect(80, 50, 81, 21))
        self.mLineEd2DmuYT.setObjectName("mLineEd2DmuYT")
        self.mLineEd2DsigYT = QtGui.QLineEdit(self.groupBox_3)
        self.mLineEd2DsigYT.setGeometry(QtCore.QRect(80, 110, 81, 21))
        self.mLineEd2DsigYT.setObjectName("mLineEd2DsigYT")
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.mLineEd2DmuXT = QtGui.QLineEdit(self.groupBox_3)
        self.mLineEd2DmuXT.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.mLineEd2DmuXT.setObjectName("mLineEd2DmuXT")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.mLineEd2DsigXT = QtGui.QLineEdit(self.groupBox_3)
        self.mLineEd2DsigXT.setGeometry(QtCore.QRect(80, 80, 81, 21))
        self.mLineEd2DsigXT.setObjectName("mLineEd2DsigXT")
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.mLineEd2DRhoT = QtGui.QLineEdit(self.groupBox_3)
        self.mLineEd2DRhoT.setGeometry(QtCore.QRect(80, 140, 81, 21))
        self.mLineEd2DRhoT.setObjectName("mLineEd2DRhoT")
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 170, 111, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.mLineEd2DMaxIter = QtGui.QLineEdit(self.page2D)
        self.mLineEd2DMaxIter.setGeometry(QtCore.QRect(120, 250, 61, 21))
        self.mLineEd2DMaxIter.setObjectName("mLineEd2DMaxIter")
        self.mLineEd2DTol = QtGui.QLineEdit(self.page2D)
        self.mLineEd2DTol.setGeometry(QtCore.QRect(380, 250, 48, 21))
        self.mLineEd2DTol.setObjectName("mLineEd2DTol")
        self.label_7 = QtGui.QLabel(self.page2D)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_14 = QtGui.QLabel(self.page2D)
        self.label_14.setGeometry(QtCore.QRect(230, 250, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.groupBox = QtGui.QGroupBox(self.page2D)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 191, 201))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.mLineEd2DmuXF = QtGui.QLineEdit(self.groupBox)
        self.mLineEd2DmuXF.setGeometry(QtCore.QRect(90, 20, 81, 21))
        self.mLineEd2DmuXF.setObjectName("mLineEd2DmuXF")
        self.mLineEd2DsigXF = QtGui.QLineEdit(self.groupBox)
        self.mLineEd2DsigXF.setGeometry(QtCore.QRect(90, 80, 81, 21))
        self.mLineEd2DsigXF.setObjectName("mLineEd2DsigXF")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.mLineEd2DmuYF = QtGui.QLineEdit(self.groupBox)
        self.mLineEd2DmuYF.setGeometry(QtCore.QRect(90, 50, 81, 21))
        self.mLineEd2DmuYF.setObjectName("mLineEd2DmuYF")
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.mLineEd2DsigYF = QtGui.QLineEdit(self.groupBox)
        self.mLineEd2DsigYF.setGeometry(QtCore.QRect(90, 110, 81, 21))
        self.mLineEd2DsigYF.setObjectName("mLineEd2DsigYF")
        self.mLineEd2DRhoF = QtGui.QLineEdit(self.groupBox)
        self.mLineEd2DRhoF.setGeometry(QtCore.QRect(90, 140, 81, 21))
        self.mLineEd2DRhoF.setObjectName("mLineEd2DRhoF")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.mLineEd2DpF = QtGui.QLineEdit(self.groupBox)
        self.mLineEd2DpF.setGeometry(QtCore.QRect(90, 170, 81, 21))
        self.mLineEd2DpF.setObjectName("mLineEd2DpF")
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 72, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.mcmbBox2DX = QtGui.QComboBox(self.page2D)
        self.mcmbBox2DX.setGeometry(QtCore.QRect(90, 10, 91, 22))
        self.mcmbBox2DX.setObjectName("mcmbBox2DX")
        self.label_29 = QtGui.QLabel(self.page2D)
        self.label_29.setGeometry(QtCore.QRect(20, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.mcmbBox2DY = QtGui.QComboBox(self.page2D)
        self.mcmbBox2DY.setGeometry(QtCore.QRect(320, 10, 91, 22))
        self.mcmbBox2DY.setObjectName("mcmbBox2DY")
        self.label_30 = QtGui.QLabel(self.page2D)
        self.label_30.setGeometry(QtCore.QRect(260, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.mstkWidgEM.addWidget(self.page2D)
        self.page3D = QtGui.QWidget()
        self.page3D.setObjectName("page3D")
        self.groupBox_6 = QtGui.QGroupBox(self.page3D)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 40, 191, 181))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_42 = QtGui.QLabel(self.groupBox_6)
        self.label_42.setGeometry(QtCore.QRect(40, 20, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.mLineEd3DmuXF = QtGui.QLineEdit(self.groupBox_6)
        self.mLineEd3DmuXF.setGeometry(QtCore.QRect(90, 20, 81, 21))
        self.mLineEd3DmuXF.setObjectName("mLineEd3DmuXF")
        self.mLineEd3DmuZF = QtGui.QLineEdit(self.groupBox_6)
        self.mLineEd3DmuZF.setGeometry(QtCore.QRect(90, 100, 81, 21))
        self.mLineEd3DmuZF.setObjectName("mLineEd3DmuZF")
        self.label_43 = QtGui.QLabel(self.groupBox_6)
        self.label_43.setGeometry(QtCore.QRect(40, 100, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtGui.QLabel(self.groupBox_6)
        self.label_44.setGeometry(QtCore.QRect(40, 60, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.mLineEd3DmuYF = QtGui.QLineEdit(self.groupBox_6)
        self.mLineEd3DmuYF.setGeometry(QtCore.QRect(90, 60, 81, 21))
        self.mLineEd3DmuYF.setObjectName("mLineEd3DmuYF")
        self.mLineEd3DpF = QtGui.QLineEdit(self.groupBox_6)
        self.mLineEd3DpF.setGeometry(QtCore.QRect(90, 140, 81, 21))
        self.mLineEd3DpF.setObjectName("mLineEd3DpF")
        self.label_47 = QtGui.QLabel(self.groupBox_6)
        self.label_47.setGeometry(QtCore.QRect(10, 140, 72, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.mLineEd3DTol = QtGui.QLineEdit(self.page3D)
        self.mLineEd3DTol.setGeometry(QtCore.QRect(380, 250, 48, 21))
        self.mLineEd3DTol.setObjectName("mLineEd3DTol")
        self.label_40 = QtGui.QLabel(self.page3D)
        self.label_40.setGeometry(QtCore.QRect(430, 250, 21, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_39 = QtGui.QLabel(self.page3D)
        self.label_39.setGeometry(QtCore.QRect(20, 250, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.mLineEd3DMaxIter = QtGui.QLineEdit(self.page3D)
        self.mLineEd3DMaxIter.setGeometry(QtCore.QRect(120, 250, 61, 21))
        self.mLineEd3DMaxIter.setObjectName("mLineEd3DMaxIter")
        self.groupBox_5 = QtGui.QGroupBox(self.page3D)
        self.groupBox_5.setGeometry(QtCore.QRect(250, 40, 181, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.mLineEd3DmuYT = QtGui.QLineEdit(self.groupBox_5)
        self.mLineEd3DmuYT.setGeometry(QtCore.QRect(80, 60, 81, 21))
        self.mLineEd3DmuYT.setObjectName("mLineEd3DmuYT")
        self.label_33 = QtGui.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(30, 60, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_35 = QtGui.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(30, 20, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.mLineEd3DmuXT = QtGui.QLineEdit(self.groupBox_5)
        self.mLineEd3DmuXT.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.mLineEd3DmuXT.setObjectName("mLineEd3DmuXT")
        self.label_36 = QtGui.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(30, 100, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_36.setObjectName("label_36")
        self.mLineEd3DmuZT = QtGui.QLineEdit(self.groupBox_5)
        self.mLineEd3DmuZT.setGeometry(QtCore.QRect(80, 100, 81, 21))
        self.mLineEd3DmuZT.setObjectName("mLineEd3DmuZT")
        self.label_38 = QtGui.QLabel(self.groupBox_5)
        self.label_38.setGeometry(QtCore.QRect(30, 140, 111, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_41 = QtGui.QLabel(self.page3D)
        self.label_41.setGeometry(QtCore.QRect(230, 250, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_18 = QtGui.QLabel(self.page3D)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 291, 21))
        self.label_18.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.mstkWidgEM.addWidget(self.page3D)
        self.mcmbBoxDim = QtGui.QComboBox(mdlgEMparameters)
        self.mcmbBoxDim.setGeometry(QtCore.QRect(150, 60, 91, 22))
        self.mcmbBoxDim.setObjectName("mcmbBoxDim")
        self.mcmbBoxDim.addItem(QtCore.QString())
        self.mcmbBoxDim.addItem(QtCore.QString())
        self.mcmbBoxDim.addItem(QtCore.QString())
        self.label_19 = QtGui.QLabel(mdlgEMparameters)
        self.label_19.setGeometry(QtCore.QRect(30, 60, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.retranslateUi(mdlgEMparameters)
        self.mstkWidgEM.setCurrentIndex(1)
        self.mcmbBoxDim.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), mdlgEMparameters.reject)
        QtCore.QObject.connect(self.mcmbBoxDim, QtCore.SIGNAL("activated(int)"), self.mstkWidgEM.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(mdlgEMparameters)

    def retranslateUi(self, mdlgEMparameters):
        mdlgEMparameters.setWindowTitle(QtGui.QApplication.translate("mdlgEMparameters", "Initial Parameters for EM", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mdlgEMparameters", "Initial Values for the Model Estimation via EM:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("mdlgEMparameters", "False Hits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (X) :", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd1DmuF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd1DsigF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.71", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("mdlgEMparameters", "σ (X) :", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd1DpF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("mdlgEMparameters", "p1 (False):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("mdlgEMparameters", "Tolarence for Likelihood:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("mdlgEMparameters", "Max. Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd1DTol.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("mdlgEMparameters", "True Hits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (X) :", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd1DmuT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("mdlgEMparameters", "σ (X) :", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd1DsigT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("mdlgEMparameters", "p2 (True) = 1 - p1", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd1DMaxIter.setText(QtGui.QApplication.translate("mdlgEMparameters", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("mdlgEMparameters", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("mdlgEMparameters", "Select X :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("mdlgEMparameters", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("mdlgEMparameters", "True Hits", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DmuYT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DsigYT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.55", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (Y):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("mdlgEMparameters", "σ (Y):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (X):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DmuXT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mdlgEMparameters", "σ (X):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DsigXT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("mdlgEMparameters", "ρ:", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DRhoT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.33", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("mdlgEMparameters", "p2 (True) = 1 - p1", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DMaxIter.setText(QtGui.QApplication.translate("mdlgEMparameters", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DTol.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mdlgEMparameters", "Max. Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("mdlgEMparameters", "Tolarence for Likelihood:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mdlgEMparameters", "False Hits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (X):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DmuXF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DsigXF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.71", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mdlgEMparameters", "σ (X):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (Y):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DmuYF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("mdlgEMparameters", "σ (Y):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DsigYF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.32", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DRhoF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mdlgEMparameters", "ρ:", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd2DpF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("mdlgEMparameters", "p1 (False):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("mdlgEMparameters", "Select X :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("mdlgEMparameters", "Select Y :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("mdlgEMparameters", "False Hits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (X):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DmuXF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DmuZF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.71", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (Z):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (Y):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DmuYF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DpF.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("mdlgEMparameters", "p1 (False):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DTol.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("mdlgEMparameters", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("mdlgEMparameters", "Max. Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DMaxIter.setText(QtGui.QApplication.translate("mdlgEMparameters", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("mdlgEMparameters", "True Hits", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DmuYT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (Y):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (X):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DmuXT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("mdlgEMparameters", "μ (Z):", None, QtGui.QApplication.UnicodeUTF8))
        self.mLineEd3DmuZT.setText(QtGui.QApplication.translate("mdlgEMparameters", "0.45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("mdlgEMparameters", "p2 (True) = 1 - p1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("mdlgEMparameters", "Tolarence for Likelihood:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("mdlgEMparameters", "Initial ∑, 3X3 matrix will be guessed for the fitting process.", None, QtGui.QApplication.UnicodeUTF8))
        self.mcmbBoxDim.setItemText(0, QtGui.QApplication.translate("mdlgEMparameters", "1 D", None, QtGui.QApplication.UnicodeUTF8))
        self.mcmbBoxDim.setItemText(1, QtGui.QApplication.translate("mdlgEMparameters", "2 D", None, QtGui.QApplication.UnicodeUTF8))
        self.mcmbBoxDim.setItemText(2, QtGui.QApplication.translate("mdlgEMparameters", "3 D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("mdlgEMparameters", "Model Dimension : ", None, QtGui.QApplication.UnicodeUTF8))

