# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Research\Python\fdr_mix_model\src\epicUIelements\dlgXTandemPara.ui'
#
# Created: Tue Dec 02 14:14:53 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mdlgXTandemPara(object):
    def setupUi(self, mdlgXTandemPara):
        mdlgXTandemPara.setObjectName("mdlgXTandemPara")
        mdlgXTandemPara.resize(343, 341)
        self.buttonBox = QtGui.QDialogButtonBox(mdlgXTandemPara)
        self.buttonBox.setGeometry(QtCore.QRect(250, 60, 81, 101))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.line_2 = QtGui.QFrame(mdlgXTandemPara)
        self.line_2.setGeometry(QtCore.QRect(19, 320, 311, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtGui.QFrame(mdlgXTandemPara)
        self.line.setGeometry(QtCore.QRect(19, 30, 311, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mlineEditDelCn2threh = QtGui.QLineEdit(mdlgXTandemPara)
        self.mlineEditDelCn2threh.setGeometry(QtCore.QRect(130, 260, 81, 21))
        self.mlineEditDelCn2threh.setObjectName("mlineEditDelCn2threh")
        self.label_8 = QtGui.QLabel(mdlgXTandemPara)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame = QtGui.QFrame(mdlgXTandemPara)
        self.frame.setGeometry(QtCore.QRect(20, 290, 211, 31))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.mchkBoxByPass = QtGui.QCheckBox(self.frame)
        self.mchkBoxByPass.setGeometry(QtCore.QRect(10, 0, 181, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.mchkBoxByPass.setFont(font)
        self.mchkBoxByPass.setChecked(False)
        self.mchkBoxByPass.setObjectName("mchkBoxByPass")
        self.groupBox = QtGui.QGroupBox(mdlgXTandemPara)
        self.groupBox.setGeometry(QtCore.QRect(19, 50, 211, 201))
        self.groupBox.setObjectName("groupBox")
        self.mchkBoxCS1 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS1.setGeometry(QtCore.QRect(30, 20, 101, 18))
        self.mchkBoxCS1.setChecked(False)
        self.mchkBoxCS1.setObjectName("mchkBoxCS1")
        self.mchkBoxCS3 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS3.setGeometry(QtCore.QRect(30, 80, 101, 18))
        self.mchkBoxCS3.setChecked(False)
        self.mchkBoxCS3.setObjectName("mchkBoxCS3")
        self.mchkBoxCS2 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS2.setGeometry(QtCore.QRect(30, 50, 101, 18))
        self.mchkBoxCS2.setChecked(True)
        self.mchkBoxCS2.setObjectName("mchkBoxCS2")
        self.mchkBoxCSother = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCSother.setGeometry(QtCore.QRect(30, 170, 151, 18))
        self.mchkBoxCSother.setChecked(False)
        self.mchkBoxCSother.setObjectName("mchkBoxCSother")
        self.label = QtGui.QLabel(mdlgXTandemPara)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mchkBoxCS4 = QtGui.QCheckBox(mdlgXTandemPara)
        self.mchkBoxCS4.setGeometry(QtCore.QRect(50, 160, 101, 18))
        self.mchkBoxCS4.setChecked(False)
        self.mchkBoxCS4.setObjectName("mchkBoxCS4")
        self.mchkBoxCS5 = QtGui.QCheckBox(mdlgXTandemPara)
        self.mchkBoxCS5.setGeometry(QtCore.QRect(50, 190, 101, 18))
        self.mchkBoxCS5.setChecked(False)
        self.mchkBoxCS5.setObjectName("mchkBoxCS5")

        self.retranslateUi(mdlgXTandemPara)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), mdlgXTandemPara.reject)
        QtCore.QMetaObject.connectSlotsByName(mdlgXTandemPara)

    def retranslateUi(self, mdlgXTandemPara):
        mdlgXTandemPara.setWindowTitle(QtGui.QApplication.translate("mdlgXTandemPara", "X!Tandem", None, QtGui.QApplication.UnicodeUTF8))
        self.mlineEditDelCn2threh.setText(QtGui.QApplication.translate("mdlgXTandemPara", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mdlgXTandemPara", "DelCn2 Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxByPass.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Bypass all the above filters", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mdlgXTandemPara", "Select Charge States", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS1.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Charge State 1", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS3.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Charge State 3", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS2.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Charge State 2", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCSother.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Charge State 6 and above", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Select X!Tandem Parameters :", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS4.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Charge State 4", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS5.setText(QtGui.QApplication.translate("mdlgXTandemPara", "Charge State 5", None, QtGui.QApplication.UnicodeUTF8))

