# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Ashoka\EclipseProjects\fdr_mix_model\src\epicUIelements\dlgSequestPara.ui'
#
# Created: Wed Sep 02 13:51:37 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mdlgSequestPara(object):
    def setupUi(self, mdlgSequestPara):
        mdlgSequestPara.setObjectName("mdlgSequestPara")
        mdlgSequestPara.resize(468, 405)
        self.buttonBox = QtGui.QDialogButtonBox(mdlgSequestPara)
        self.buttonBox.setGeometry(QtCore.QRect(100, 360, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(mdlgSequestPara)
        self.label.setGeometry(QtCore.QRect(21, 20, 261, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtGui.QFrame(mdlgSequestPara)
        self.line.setGeometry(QtCore.QRect(20, 40, 431, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(mdlgSequestPara)
        self.line_2.setGeometry(QtCore.QRect(20, 340, 431, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox = QtGui.QGroupBox(mdlgSequestPara)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 211, 201))
        self.groupBox.setObjectName("groupBox")
        self.mchkBoxCS1 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS1.setGeometry(QtCore.QRect(30, 20, 101, 18))
        self.mchkBoxCS1.setChecked(False)
        self.mchkBoxCS1.setObjectName("mchkBoxCS1")
        self.mchkBoxCS3 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS3.setGeometry(QtCore.QRect(30, 80, 101, 18))
        self.mchkBoxCS3.setChecked(False)
        self.mchkBoxCS3.setObjectName("mchkBoxCS3")
        self.mchkBoxCS2 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS2.setGeometry(QtCore.QRect(30, 50, 101, 18))
        self.mchkBoxCS2.setChecked(True)
        self.mchkBoxCS2.setObjectName("mchkBoxCS2")
        self.mchkBoxCSother = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCSother.setGeometry(QtCore.QRect(30, 170, 151, 18))
        self.mchkBoxCSother.setChecked(False)
        self.mchkBoxCSother.setObjectName("mchkBoxCSother")
        self.mchkBoxCS4 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS4.setGeometry(QtCore.QRect(30, 110, 101, 18))
        self.mchkBoxCS4.setChecked(False)
        self.mchkBoxCS4.setObjectName("mchkBoxCS4")
        self.mchkBoxCS5 = QtGui.QCheckBox(self.groupBox)
        self.mchkBoxCS5.setGeometry(QtCore.QRect(30, 140, 101, 18))
        self.mchkBoxCS5.setChecked(False)
        self.mchkBoxCS5.setObjectName("mchkBoxCS5")
        self.groupBox_2 = QtGui.QGroupBox(mdlgSequestPara)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 60, 211, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.mchkBoxNone = QtGui.QCheckBox(self.groupBox_2)
        self.mchkBoxNone.setGeometry(QtCore.QRect(30, 30, 71, 18))
        self.mchkBoxNone.setChecked(True)
        self.mchkBoxNone.setObjectName("mchkBoxNone")
        self.mchkBoxPartial = QtGui.QCheckBox(self.groupBox_2)
        self.mchkBoxPartial.setGeometry(QtCore.QRect(30, 100, 71, 18))
        self.mchkBoxPartial.setChecked(True)
        self.mchkBoxPartial.setObjectName("mchkBoxPartial")
        self.mchkBoxFull = QtGui.QCheckBox(self.groupBox_2)
        self.mchkBoxFull.setGeometry(QtCore.QRect(30, 170, 71, 18))
        self.mchkBoxFull.setChecked(True)
        self.mchkBoxFull.setObjectName("mchkBoxFull")
        self.label_7 = QtGui.QLabel(mdlgSequestPara)
        self.label_7.setGeometry(QtCore.QRect(30, 270, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(mdlgSequestPara)
        self.label_8.setGeometry(QtCore.QRect(240, 270, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.mspinBoxMaxXc = QtGui.QSpinBox(mdlgSequestPara)
        self.mspinBoxMaxXc.setGeometry(QtCore.QRect(130, 270, 81, 22))
        self.mspinBoxMaxXc.setMinimum(1)
        self.mspinBoxMaxXc.setMaximum(10)
        self.mspinBoxMaxXc.setProperty("value", QtCore.QVariant(1))
        self.mspinBoxMaxXc.setObjectName("mspinBoxMaxXc")
        self.mlineEditDelCn2threh = QtGui.QLineEdit(mdlgSequestPara)
        self.mlineEditDelCn2threh.setGeometry(QtCore.QRect(340, 270, 81, 21))
        self.mlineEditDelCn2threh.setObjectName("mlineEditDelCn2threh")
        self.frame = QtGui.QFrame(mdlgSequestPara)
        self.frame.setGeometry(QtCore.QRect(20, 300, 211, 41))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.mchkBoxByPass = QtGui.QCheckBox(self.frame)
        self.mchkBoxByPass.setGeometry(QtCore.QRect(10, 10, 181, 18))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.mchkBoxByPass.setFont(font)
        self.mchkBoxByPass.setChecked(False)
        self.mchkBoxByPass.setObjectName("mchkBoxByPass")

        self.retranslateUi(mdlgSequestPara)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), mdlgSequestPara.reject)
        QtCore.QMetaObject.connectSlotsByName(mdlgSequestPara)

    def retranslateUi(self, mdlgSequestPara):
        mdlgSequestPara.setWindowTitle(QtGui.QApplication.translate("mdlgSequestPara", "Sequest", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mdlgSequestPara", "Select SEQUEST Parameters :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mdlgSequestPara", "Select Charge States", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS1.setText(QtGui.QApplication.translate("mdlgSequestPara", "Charge State 1", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS3.setText(QtGui.QApplication.translate("mdlgSequestPara", "Charge State 3", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS2.setText(QtGui.QApplication.translate("mdlgSequestPara", "Charge State 2", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCSother.setText(QtGui.QApplication.translate("mdlgSequestPara", "Charge State 6 and above", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS4.setText(QtGui.QApplication.translate("mdlgSequestPara", "Charge State 4", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxCS5.setText(QtGui.QApplication.translate("mdlgSequestPara", "Charge State 5", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("mdlgSequestPara", "Tryptic State", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxNone.setText(QtGui.QApplication.translate("mdlgSequestPara", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxPartial.setText(QtGui.QApplication.translate("mdlgSequestPara", "Partial", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxFull.setText(QtGui.QApplication.translate("mdlgSequestPara", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mdlgSequestPara", "Max XCorr Rank:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mdlgSequestPara", "DelCn2 Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.mlineEditDelCn2threh.setText(QtGui.QApplication.translate("mdlgSequestPara", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.mchkBoxByPass.setText(QtGui.QApplication.translate("mdlgSequestPara", "Bypass all the above filters", None, QtGui.QApplication.UnicodeUTF8))

