# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Ashoka\EclipseProjects\fdr_mix_model\src\epicUIelements\epic.ui'
#
# Created: Thu Sep 03 15:53:29 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mMainWindowEpic(object):
    def setupUi(self, mMainWindowEpic):
        mMainWindowEpic.setObjectName("mMainWindowEpic")
        mMainWindowEpic.resize(831, 691)
        self.centralwidget = QtGui.QWidget(mMainWindowEpic)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mtabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mtabWidget.sizePolicy().hasHeightForWidth())
        self.mtabWidget.setSizePolicy(sizePolicy)
        self.mtabWidget.setObjectName("mtabWidget")
        self.mTabData = QtGui.QWidget()
        self.mTabData.setObjectName("mTabData")
        self.vboxlayout = QtGui.QVBoxLayout(self.mTabData)
        self.vboxlayout.setObjectName("vboxlayout")
        self.mTableView = QtGui.QTableView(self.mTabData)
        self.mTableView.setObjectName("mTableView")
        self.vboxlayout.addWidget(self.mTableView)
        self.mtabWidget.addTab(self.mTabData, "")
        self.mTabPlot = QtGui.QWidget()
        self.mTabPlot.setObjectName("mTabPlot")
        self.horizontalLayout = QtGui.QHBoxLayout(self.mTabPlot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.matplotlibWidget = MPLWidget(self.mTabPlot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibWidget.sizePolicy().hasHeightForWidth())
        self.matplotlibWidget.setSizePolicy(sizePolicy)
        self.matplotlibWidget.setObjectName("matplotlibWidget")
        self.horizontalLayout.addWidget(self.matplotlibWidget)
        self.dockWidget = QtGui.QDockWidget(self.mTabPlot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(111, 486))
        self.dockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.mrBtnRawPlots = QtGui.QRadioButton(self.dockWidgetContents)
        self.mrBtnRawPlots.setGeometry(QtCore.QRect(20, 10, 64, 18))
        self.mrBtnRawPlots.setChecked(True)
        self.mrBtnRawPlots.setObjectName("mrBtnRawPlots")
        self.mrBtnNormedPlots = QtGui.QRadioButton(self.dockWidgetContents)
        self.mrBtnNormedPlots.setGeometry(QtCore.QRect(20, 30, 81, 18))
        self.mrBtnNormedPlots.setObjectName("mrBtnNormedPlots")
        self.mbtnFDRregions = QtGui.QPushButton(self.dockWidgetContents)
        self.mbtnFDRregions.setGeometry(QtCore.QRect(20, 380, 64, 23))
        self.mbtnFDRregions.setObjectName("mbtnFDRregions")
        self.mbtnContours = QtGui.QPushButton(self.dockWidgetContents)
        self.mbtnContours.setGeometry(QtCore.QRect(20, 350, 63, 23))
        self.mbtnContours.setObjectName("mbtnContours")
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 91, 111))
        self.groupBox.setObjectName("groupBox")
        self.mbtnX_vs_Y = QtGui.QPushButton(self.groupBox)
        self.mbtnX_vs_Y.setGeometry(QtCore.QRect(10, 20, 63, 23))
        self.mbtnX_vs_Y.setObjectName("mbtnX_vs_Y")
        self.mbtnX_vs_Z = QtGui.QPushButton(self.groupBox)
        self.mbtnX_vs_Z.setGeometry(QtCore.QRect(10, 50, 64, 23))
        self.mbtnX_vs_Z.setObjectName("mbtnX_vs_Z")
        self.mbtnY_vs_Z = QtGui.QPushButton(self.groupBox)
        self.mbtnY_vs_Z.setGeometry(QtCore.QRect(10, 80, 63, 23))
        self.mbtnY_vs_Z.setObjectName("mbtnY_vs_Z")
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 91, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.mbtnHistX = QtGui.QPushButton(self.groupBox_2)
        self.mbtnHistX.setGeometry(QtCore.QRect(10, 70, 64, 23))
        self.mbtnHistX.setObjectName("mbtnHistX")
        self.mbtnHistY = QtGui.QPushButton(self.groupBox_2)
        self.mbtnHistY.setGeometry(QtCore.QRect(10, 100, 63, 23))
        self.mbtnHistY.setObjectName("mbtnHistY")
        self.mbtnHistZ = QtGui.QPushButton(self.groupBox_2)
        self.mbtnHistZ.setGeometry(QtCore.QRect(10, 130, 64, 23))
        self.mbtnHistZ.setObjectName("mbtnHistZ")
        self.mlineEdBins = QtGui.QLineEdit(self.groupBox_2)
        self.mlineEdBins.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.mlineEdBins.setObjectName("mlineEdBins")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 14))
        self.label.setObjectName("label")
        self.mbtnSaveFigure = QtGui.QPushButton(self.dockWidgetContents)
        self.mbtnSaveFigure.setGeometry(QtCore.QRect(20, 410, 64, 23))
        self.mbtnSaveFigure.setObjectName("mbtnSaveFigure")
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.mtabWidget.addTab(self.mTabPlot, "")
        self.mTabMessages = QtGui.QWidget()
        self.mTabMessages.setObjectName("mTabMessages")
        self.gridlayout = QtGui.QGridLayout(self.mTabMessages)
        self.gridlayout.setObjectName("gridlayout")
        self.mlstViewMessages = QtGui.QListView(self.mTabMessages)
        self.mlstViewMessages.setObjectName("mlstViewMessages")
        self.gridlayout.addWidget(self.mlstViewMessages, 0, 0, 1, 1)
        self.mtabWidget.addTab(self.mTabMessages, "")
        self.verticalLayout.addWidget(self.mtabWidget)
        mMainWindowEpic.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mMainWindowEpic)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEstimate = QtGui.QMenu(self.menubar)
        self.menuEstimate.setObjectName("menuEstimate")
        self.menuCompute_q_values = QtGui.QMenu(self.menuEstimate)
        self.menuCompute_q_values.setObjectName("menuCompute_q_values")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.mnuPlot = QtGui.QMenu(self.menubar)
        self.mnuPlot.setObjectName("mnuPlot")
        self.mnuPlotRawData = QtGui.QMenu(self.mnuPlot)
        self.mnuPlotRawData.setObjectName("mnuPlotRawData")
        self.mnuPlotNormData = QtGui.QMenu(self.mnuPlot)
        self.mnuPlotNormData.setObjectName("mnuPlotNormData")
        self.menuHistograms = QtGui.QMenu(self.mnuPlot)
        self.menuHistograms.setObjectName("menuHistograms")
        self.menuHistogram_Normalized_2 = QtGui.QMenu(self.mnuPlot)
        self.menuHistogram_Normalized_2.setObjectName("menuHistogram_Normalized_2")
        self.menuContour_Lines = QtGui.QMenu(self.mnuPlot)
        self.menuContour_Lines.setObjectName("menuContour_Lines")
        self.menuContour_Surfaces = QtGui.QMenu(self.mnuPlot)
        self.menuContour_Surfaces.setObjectName("menuContour_Surfaces")
        mMainWindowEpic.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mMainWindowEpic)
        self.statusbar.setObjectName("statusbar")
        mMainWindowEpic.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(mMainWindowEpic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        mMainWindowEpic.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.mnuExit = QtGui.QAction(mMainWindowEpic)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuExit.setIcon(icon)
        self.mnuExit.setObjectName("mnuExit")
        self.mnuFitMixed = QtGui.QAction(mMainWindowEpic)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuFitMixed.setIcon(icon1)
        self.mnuFitMixed.setObjectName("mnuFitMixed")
        self.mnuAbout = QtGui.QAction(mMainWindowEpic)
        self.mnuAbout.setObjectName("mnuAbout")
        self.mnuNormalize = QtGui.QAction(mMainWindowEpic)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/normalization.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuNormalize.setIcon(icon2)
        self.mnuNormalize.setObjectName("mnuNormalize")
        self.mnuSaveData = QtGui.QAction(mMainWindowEpic)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/FileSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuSaveData.setIcon(icon3)
        self.mnuSaveData.setObjectName("mnuSaveData")
        self.mnuOpenFlatFile = QtGui.QAction(mMainWindowEpic)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/openHS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuOpenFlatFile.setIcon(icon4)
        self.mnuOpenFlatFile.setObjectName("mnuOpenFlatFile")
        self.mnuOpenSynFiles = QtGui.QAction(mMainWindowEpic)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/OpenSelectedItemHS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuOpenSynFiles.setIcon(icon5)
        self.mnuOpenSynFiles.setObjectName("mnuOpenSynFiles")
        self.mnuDCnHist = QtGui.QAction(mMainWindowEpic)
        self.mnuDCnHist.setObjectName("mnuDCnHist")
        self.mnuFDRregions = QtGui.QAction(mMainWindowEpic)
        self.mnuFDRregions.setEnabled(True)
        self.mnuFDRregions.setObjectName("mnuFDRregions")
        self.mnuRawX_vs_Y = QtGui.QAction(mMainWindowEpic)
        self.mnuRawX_vs_Y.setObjectName("mnuRawX_vs_Y")
        self.mnuRawX_vs_Z = QtGui.QAction(mMainWindowEpic)
        self.mnuRawX_vs_Z.setObjectName("mnuRawX_vs_Z")
        self.mnuRawY_vs_Z = QtGui.QAction(mMainWindowEpic)
        self.mnuRawY_vs_Z.setObjectName("mnuRawY_vs_Z")
        self.mnuNormX_vs_Y = QtGui.QAction(mMainWindowEpic)
        self.mnuNormX_vs_Y.setObjectName("mnuNormX_vs_Y")
        self.mnuNormX_vs_Z = QtGui.QAction(mMainWindowEpic)
        self.mnuNormX_vs_Z.setObjectName("mnuNormX_vs_Z")
        self.mnuNormY_vs_Z = QtGui.QAction(mMainWindowEpic)
        self.mnuNormY_vs_Z.setObjectName("mnuNormY_vs_Z")
        self.mnuRawHistX = QtGui.QAction(mMainWindowEpic)
        self.mnuRawHistX.setObjectName("mnuRawHistX")
        self.mnuRawHistY = QtGui.QAction(mMainWindowEpic)
        self.mnuRawHistY.setObjectName("mnuRawHistY")
        self.mnuRawHistZ = QtGui.QAction(mMainWindowEpic)
        self.mnuRawHistZ.setObjectName("mnuRawHistZ")
        self.mnuSelectVars = QtGui.QAction(mMainWindowEpic)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/selVars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuSelectVars.setIcon(icon6)
        self.mnuSelectVars.setObjectName("mnuSelectVars")
        self.mnuTogglePlotBtns = QtGui.QAction(mMainWindowEpic)
        self.mnuTogglePlotBtns.setObjectName("mnuTogglePlotBtns")
        self.mnuOpenFile = QtGui.QAction(mMainWindowEpic)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/FileOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuOpenFile.setIcon(icon7)
        self.mnuOpenFile.setObjectName("mnuOpenFile")
        self.mnuSelectVarsSEQUEST = QtGui.QAction(mMainWindowEpic)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/selSEQ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuSelectVarsSEQUEST.setIcon(icon8)
        self.mnuSelectVarsSEQUEST.setObjectName("mnuSelectVarsSEQUEST")
        self.mnuSelectVarsXTandem = QtGui.QAction(mMainWindowEpic)
        self.mnuSelectVarsXTandem.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/selXT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuSelectVarsXTandem.setIcon(icon9)
        self.mnuSelectVarsXTandem.setObjectName("mnuSelectVarsXTandem")
        self.actionX = QtGui.QAction(mMainWindowEpic)
        self.actionX.setObjectName("actionX")
        self.mnuNormHistX = QtGui.QAction(mMainWindowEpic)
        self.mnuNormHistX.setObjectName("mnuNormHistX")
        self.mnuNormHistY = QtGui.QAction(mMainWindowEpic)
        self.mnuNormHistY.setObjectName("mnuNormHistY")
        self.mnuNormHistZ = QtGui.QAction(mMainWindowEpic)
        self.mnuNormHistZ.setObjectName("mnuNormHistZ")
        self.mnuSaveMessages = QtGui.QAction(mMainWindowEpic)
        self.mnuSaveMessages.setObjectName("mnuSaveMessages")
        self.mnuSelectVarsSpectrumMill = QtGui.QAction(mMainWindowEpic)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/selSM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuSelectVarsSpectrumMill.setIcon(icon10)
        self.mnuSelectVarsSpectrumMill.setObjectName("mnuSelectVarsSpectrumMill")
        self.mnuFDRPerformance = QtGui.QAction(mMainWindowEpic)
        self.mnuFDRPerformance.setObjectName("mnuFDRPerformance")
        self.mnuContourLinesPoints = QtGui.QAction(mMainWindowEpic)
        self.mnuContourLinesPoints.setObjectName("mnuContourLinesPoints")
        self.mnuContourLinesOnly = QtGui.QAction(mMainWindowEpic)
        self.mnuContourLinesOnly.setObjectName("mnuContourLinesOnly")
        self.mnuContourSurfPoints = QtGui.QAction(mMainWindowEpic)
        self.mnuContourSurfPoints.setObjectName("mnuContourSurfPoints")
        self.mnuContourSurfOnly = QtGui.QAction(mMainWindowEpic)
        self.mnuContourSurfOnly.setObjectName("mnuContourSurfOnly")
        self.mnupBayes = QtGui.QAction(mMainWindowEpic)
        self.mnupBayes.setObjectName("mnupBayes")
        self.mnupGVol = QtGui.QAction(mMainWindowEpic)
        self.mnupGVol.setObjectName("mnupGVol")
        self.mnupGVolC = QtGui.QAction(mMainWindowEpic)
        self.mnupGVolC.setObjectName("mnupGVolC")
        self.mnuCompute_q_vals = QtGui.QAction(mMainWindowEpic)
        self.mnuCompute_q_vals.setObjectName("mnuCompute_q_vals")
        self.menuFile.addAction(self.mnuOpenFile)
        self.menuFile.addAction(self.mnuSaveData)
        self.menuFile.addAction(self.mnuSaveMessages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.mnuExit)
        self.menuCompute_q_values.addAction(self.mnupBayes)
        self.menuCompute_q_values.addAction(self.mnupGVol)
        self.menuCompute_q_values.addAction(self.mnupGVolC)
        self.menuEstimate.addAction(self.mnuSelectVarsSEQUEST)
        self.menuEstimate.addAction(self.mnuSelectVarsXTandem)
        self.menuEstimate.addAction(self.mnuSelectVarsSpectrumMill)
        self.menuEstimate.addAction(self.mnuSelectVars)
        self.menuEstimate.addSeparator()
        self.menuEstimate.addAction(self.mnuNormalize)
        self.menuEstimate.addAction(self.mnuFitMixed)
        self.menuEstimate.addAction(self.mnuCompute_q_vals)
        self.menuEstimate.addAction(self.menuCompute_q_values.menuAction())
        self.menu.addAction(self.mnuAbout)
        self.mnuPlotRawData.addAction(self.mnuRawX_vs_Y)
        self.mnuPlotRawData.addAction(self.mnuRawX_vs_Z)
        self.mnuPlotRawData.addAction(self.mnuRawY_vs_Z)
        self.mnuPlotNormData.addAction(self.mnuNormX_vs_Y)
        self.mnuPlotNormData.addAction(self.mnuNormX_vs_Z)
        self.mnuPlotNormData.addAction(self.mnuNormY_vs_Z)
        self.menuHistograms.addAction(self.mnuRawHistX)
        self.menuHistograms.addAction(self.mnuRawHistY)
        self.menuHistograms.addAction(self.mnuRawHistZ)
        self.menuHistogram_Normalized_2.addAction(self.mnuNormHistX)
        self.menuHistogram_Normalized_2.addAction(self.mnuNormHistY)
        self.menuHistogram_Normalized_2.addAction(self.mnuNormHistZ)
        self.menuContour_Lines.addAction(self.mnuContourLinesPoints)
        self.menuContour_Lines.addAction(self.mnuContourLinesOnly)
        self.menuContour_Surfaces.addAction(self.mnuContourSurfPoints)
        self.menuContour_Surfaces.addAction(self.mnuContourSurfOnly)
        self.mnuPlot.addAction(self.mnuPlotRawData.menuAction())
        self.mnuPlot.addAction(self.mnuPlotNormData.menuAction())
        self.mnuPlot.addSeparator()
        self.mnuPlot.addAction(self.menuHistograms.menuAction())
        self.mnuPlot.addAction(self.menuHistogram_Normalized_2.menuAction())
        self.mnuPlot.addAction(self.menuContour_Surfaces.menuAction())
        self.mnuPlot.addAction(self.menuContour_Lines.menuAction())
        self.mnuPlot.addAction(self.mnuFDRregions)
        self.mnuPlot.addAction(self.mnuFDRPerformance)
        self.mnuPlot.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEstimate.menuAction())
        self.menubar.addAction(self.mnuPlot.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.mnuOpenFile)
        self.toolBar.addAction(self.mnuSaveData)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.mnuSelectVarsSEQUEST)
        self.toolBar.addAction(self.mnuSelectVarsXTandem)
        self.toolBar.addAction(self.mnuSelectVarsSpectrumMill)
        self.toolBar.addAction(self.mnuSelectVars)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.mnuNormalize)
        self.toolBar.addAction(self.mnuFitMixed)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.mnuExit)

        self.retranslateUi(mMainWindowEpic)
        self.mtabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.mnuExit, QtCore.SIGNAL("triggered()"), mMainWindowEpic.close)
        QtCore.QMetaObject.connectSlotsByName(mMainWindowEpic)

    def retranslateUi(self, mMainWindowEpic):
        mMainWindowEpic.setWindowTitle(QtGui.QApplication.translate("mMainWindowEpic", "epic", None, QtGui.QApplication.UnicodeUTF8))
        self.mtabWidget.setTabText(self.mtabWidget.indexOf(self.mTabData), QtGui.QApplication.translate("mMainWindowEpic", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("mMainWindowEpic", "Plot Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.mrBtnRawPlots.setText(QtGui.QApplication.translate("mMainWindowEpic", "Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.mrBtnNormedPlots.setText(QtGui.QApplication.translate("mMainWindowEpic", "Normalized", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnFDRregions.setText(QtGui.QApplication.translate("mMainWindowEpic", "FDR region", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnContours.setText(QtGui.QApplication.translate("mMainWindowEpic", "Contours", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Scatter Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnX_vs_Y.setText(QtGui.QApplication.translate("mMainWindowEpic", "X vs. Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnX_vs_Z.setText(QtGui.QApplication.translate("mMainWindowEpic", "X vs. Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnY_vs_Z.setText(QtGui.QApplication.translate("mMainWindowEpic", "Y vs. Z", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Histograms", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnHistX.setText(QtGui.QApplication.translate("mMainWindowEpic", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnHistY.setText(QtGui.QApplication.translate("mMainWindowEpic", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnHistZ.setText(QtGui.QApplication.translate("mMainWindowEpic", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mlineEdBins.setText(QtGui.QApplication.translate("mMainWindowEpic", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mMainWindowEpic", "Bins :", None, QtGui.QApplication.UnicodeUTF8))
        self.mbtnSaveFigure.setText(QtGui.QApplication.translate("mMainWindowEpic", "Save Figure", None, QtGui.QApplication.UnicodeUTF8))
        self.mtabWidget.setTabText(self.mtabWidget.indexOf(self.mTabPlot), QtGui.QApplication.translate("mMainWindowEpic", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.mtabWidget.setTabText(self.mtabWidget.indexOf(self.mTabMessages), QtGui.QApplication.translate("mMainWindowEpic", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEstimate.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "&Process", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCompute_q_values.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "q-values (other cases)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuPlot.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Plo&t", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuPlotRawData.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Raw Data", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuPlotNormData.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Normalized Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHistograms.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Histograms (Raw)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHistogram_Normalized_2.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Histograms (Normalized)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuContour_Lines.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Contour Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.menuContour_Surfaces.setTitle(QtGui.QApplication.translate("mMainWindowEpic", "Contour Surfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("mMainWindowEpic", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuExit.setText(QtGui.QApplication.translate("mMainWindowEpic", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFitMixed.setText(QtGui.QApplication.translate("mMainWindowEpic", "Fit Gaussian &Mixture", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuAbout.setText(QtGui.QApplication.translate("mMainWindowEpic", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuNormalize.setText(QtGui.QApplication.translate("mMainWindowEpic", "&Normalize", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSaveData.setText(QtGui.QApplication.translate("mMainWindowEpic", "&Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSaveData.setShortcut(QtGui.QApplication.translate("mMainWindowEpic", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuOpenFlatFile.setText(QtGui.QApplication.translate("mMainWindowEpic", "Flat File", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuOpenSynFiles.setText(QtGui.QApplication.translate("mMainWindowEpic", "Synopsis/First hit Files", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuDCnHist.setText(QtGui.QApplication.translate("mMainWindowEpic", "DelCn2 Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFDRregions.setText(QtGui.QApplication.translate("mMainWindowEpic", "FDR Cutoff Regions", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuRawX_vs_Y.setText(QtGui.QApplication.translate("mMainWindowEpic", "X vs. Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuRawX_vs_Z.setText(QtGui.QApplication.translate("mMainWindowEpic", "X vs. Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuRawY_vs_Z.setText(QtGui.QApplication.translate("mMainWindowEpic", "Y vs. Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuNormX_vs_Y.setText(QtGui.QApplication.translate("mMainWindowEpic", "X vs. Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuNormX_vs_Z.setText(QtGui.QApplication.translate("mMainWindowEpic", "X vs. Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuNormY_vs_Z.setText(QtGui.QApplication.translate("mMainWindowEpic", "Y vs. Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuRawHistX.setText(QtGui.QApplication.translate("mMainWindowEpic", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuRawHistY.setText(QtGui.QApplication.translate("mMainWindowEpic", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuRawHistZ.setText(QtGui.QApplication.translate("mMainWindowEpic", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSelectVars.setText(QtGui.QApplication.translate("mMainWindowEpic", "Select Variables (Generic)", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuTogglePlotBtns.setText(QtGui.QApplication.translate("mMainWindowEpic", "Show Plot Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuOpenFile.setText(QtGui.QApplication.translate("mMainWindowEpic", "&Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSelectVarsSEQUEST.setText(QtGui.QApplication.translate("mMainWindowEpic", "Select Variables (Sequest)", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSelectVarsXTandem.setText(QtGui.QApplication.translate("mMainWindowEpic", "Select Variables (X!Tandem)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX.setText(QtGui.QApplication.translate("mMainWindowEpic", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuNormHistX.setText(QtGui.QApplication.translate("mMainWindowEpic", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuNormHistY.setText(QtGui.QApplication.translate("mMainWindowEpic", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuNormHistZ.setText(QtGui.QApplication.translate("mMainWindowEpic", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSaveMessages.setText(QtGui.QApplication.translate("mMainWindowEpic", "Save Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSelectVarsSpectrumMill.setText(QtGui.QApplication.translate("mMainWindowEpic", "Select Variables (Spectrum Mill)", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFDRPerformance.setText(QtGui.QApplication.translate("mMainWindowEpic", "FDR Performance", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuContourLinesPoints.setText(QtGui.QApplication.translate("mMainWindowEpic", "Show Data Points", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuContourLinesOnly.setText(QtGui.QApplication.translate("mMainWindowEpic", "Contours Only", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuContourSurfPoints.setText(QtGui.QApplication.translate("mMainWindowEpic", "Show Data Points", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuContourSurfOnly.setText(QtGui.QApplication.translate("mMainWindowEpic", "Surfaces Only", None, QtGui.QApplication.UnicodeUTF8))
        self.mnupBayes.setText(QtGui.QApplication.translate("mMainWindowEpic", "pBayes", None, QtGui.QApplication.UnicodeUTF8))
        self.mnupGVol.setText(QtGui.QApplication.translate("mMainWindowEpic", "pGVol", None, QtGui.QApplication.UnicodeUTF8))
        self.mnupGVolC.setText(QtGui.QApplication.translate("mMainWindowEpic", "pGVolC", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuCompute_q_vals.setText(QtGui.QApplication.translate("mMainWindowEpic", "q-values for 2D model", None, QtGui.QApplication.UnicodeUTF8))

from MatplotlibCustomWidget import MPLWidget
import qrc_epicResources
